[package]
name = "tsl2591-rs"
version = "0.1.4"
edition = "2024"
license = "BSD-3-Clause"
authors = ["Carlos Vásquez <carlosvassan@email.com>"]
description = "Platform-agnostic driver for the TSL2591 high dynamic range digital light sensor"
repository = "https://github.com/karlosvas/tsl2591-rs"
readme = "README.md"
keywords = ["tsl2591", "sensor", "embedded-hal", "i2c", "light-sensor"]
categories = ["embedded", "hardware-support", "no-std"]

[dependencies]
embedded-hal = "1.0"
embedded-hal-async = { version = "1.0.0", optional = true }
serde = { version = "1", features = ["derive"], optional = true }

[features]
serde = ["dep:serde"]
async = ["dep:embedded-hal-async"]

[target.'cfg(target_os = "linux")'.dev-dependencies]
linux-embedded-hal = "0.4"

[[example]]
name = "websocket"
required-features = ["serde"]

[[example]]
name = "basic"

[dev-dependencies]
tokio-tungstenite = "0.29"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
bincode = { version = "2", features = ["serde"] }
dotenvy = "0.15"